media:
  input: static/images
  output: /images

content:
  - name: posts
    label: 文章
    type: collection
    path: content/posts
    format: toml-frontmatter
    filename: "{year}-{month}-{day}-{primary}.md"
    view:
      fields: [title, categories, date, draft]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: 标题
        type: string
        required: true
      - name: date
        label: 发布时间
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss
      - name: draft
        label: 保存为草稿
        type: boolean
        default: false
      - name: categories
        label: 主分类
        required: true
        description: 从“分类管理”中搜索并选择一个分类。
        type: reference
        options:
          collection: taxonomy-categories
          search: name
          value: "{fields.name}"
          label: "{fields.name}"
          multiple: true
          min: 1
          max: 1
      - name: tags
        label: 标签
        description: 从“标签管理”中搜索并选择，可多选。
        type: reference
        options:
          collection: taxonomy-tags
          search: name
          value: "{fields.name}"
          label: "{fields.name}"
          multiple: true
      - name: featured_image
        label: 封面图片
        type: image
      - name: body
        label: 正文
        type: rich-text
  - name: taxonomy-categories
    label: 分类管理
    type: collection
    path: data/taxonomy/categories
    format: json
    filename: "{id}.json"
    view:
      fields: [name]
      primary: name
      sort: [name]
    fields:
      - name: id
        type: uuid
        hidden: true
      - name: name
        label: 分类名称
        type: string
        required: true
  - name: taxonomy-tags
    label: 标签管理
    type: collection
    path: data/taxonomy/tags
    format: json
    filename: "{id}.json"
    view:
      fields: [name]
      primary: name
      sort: [name]
    fields:
      - name: id
        type: uuid
        hidden: true
      - name: name
        label: 标签名称
        type: string
        required: true
