baseURL = "https://blog.xingyexiaohua.xyz/"
locale = "zh-CN"
defaultContentLanguage = "zh-cn"
timeZone = "Asia/Shanghai"
title = "小花の博客"
theme = "ananke"

[languages]
  [languages.zh-cn]
    label = "简体中文"
    locale = "zh-CN"
    weight = 1

[params]
  description = "记录技术、生活与沿途的灵感"
  author = "星野小花"
  hero_image = "/images/heroes/hero (2).webp"
  avatar = "/images/image.png"

  [params.giscus]
    repo = "xyxhdesu/my-blog"
    repo_id = "R_kgDOTl4IkQ"
    category = "Announcements"
    category_id = "DIC_kwDOTl4Ikc4DCKCm"
