baseURL = "https://blog.xingyexiaohua.xyz/"
locale = "zh-CN"
defaultContentLanguage = "zh-cn"
timeZone = "Asia/Shanghai"
title = "小花の博客"
theme = "ananke"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"

[related]
  includeNewer = true
  threshold = 10

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 70

[languages]
  [languages.zh-cn]
    label = "简体中文"
    locale = "zh-CN"
    weight = 1

[params]
  description = "于异世界一隅，记录未完待续的冒险。"
  author = "星野小花"
  hero_image = "/images/heroes/hero (2).webp"
  avatar = "/images/image.png"

  morning_report_endpoint = "/api/morning-report"
  site_started_at = "2026-07-28T00:00:00+08:00"

  [params.live2d]
    enabled = true

[params.giscus]
    repo = "xyxhdesu/my-blog"
    repo_id = "R_kgDOTl4IkQ"
    category = "Announcements"
    category_id = "DIC_kwDOTl4Ikc4DCKCm"
